# Site settings
title: FLOW
email: flowgeorgia.ngo@gmail.com
# this means to ignore newlines until "baseurl:"
description: Flow descr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: flowngo
github_username: flowngo

# Build settings
markdown: kramdown
logo: img/logo/logo-flow.png

social:
  - icon:	twitter
    url:	https://twitter.com/flowngo
    desc: Follow us on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
  - icon: linkedin
    url:	https://www.linkedin.com/company/flow-future-leaders-for-open-world/
    desc: Follow us on LinkedIn
    share_url: http://www.linkedin.com/share
    share_title: ?text=
    share_link: "&amp;url="
  - icon: facebook
    url: https://www.facebook.com/flowglobalngo
    desc: Follow us on Facebook
