# Site settings
title: FLOW
email: flowgeorgia.ngo@gmail.com
# this means to ignore newlines until "baseurl:"
description: Flow descr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: flowngo
github_username: flowngo

# Build settings
markdown: kramdown
logo: img/logo/wave.png

social:
  - icon:	twitter
    url:	https://twitter.com/flowngo
    desc: Follow us on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="
